name: Back

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_PAT }}
      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          coverage: xdebug
      - name: Update dependencies in lock file
        run: |
          cd Back
          docker-compose build
          docker-compose up -d
          docker-compose exec -T app bash
          composer update

      # Runs a set of commands using the runners shell
      - name: Installation Docker
        run: |
          cd Back
          docker-compose build
          docker-compose up -d
      - name: Docker PS
        run: docker ps -a
      - name: Installation Composer
        run: |
          cd Back
          docker-compose exec -T app bash
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Migration env=test
        run: |
          cd Back
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:migrations:migrate -n --env=test
      - name: Doctrine
        run: |
          cd Back
          docker-compose exec -T app bash
          php bin/console doctrine:fixtures:load -n --env=test
      - name: Lancement des test
        run: |
          cd Back
          docker-compose exec -T app bash
          composer test
      - name: Upload Code Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unit_tests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
        
