name: Back CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name : Checkout 
      uses: actions/checkout@v2
    - name : php composer
      uses: php-actions/composer@v5 # or alternative dependency management
    - name : php unit
      uses: php-actions/phpunit@v3
    - name : Test 
      run : |
        cd Back
        php bin/phpunit
