name: Back CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name : Checkout 
      uses: actions/checkout@v2
    - name : Test 
      run : |
        cd Back
        docker-compose build
        docker-compose up -d
        docker ps -a
        docker-compose -f docker-compose.yml
        docker-compose exec -T app composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        docker-compose exec -T app php bin/console doctrine:database:create --env=test
        docker-compose exec -T app php bin/console doctrine:migrations:migrate -n --env=test
        docker-compose exec -T app php bin/console doctrine:fixtures:load -n --env=test
        docker-compose exec -T app php bin/phpunit
