name: Back CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name : Checkout 
      uses: actions/checkout@v2
    - name : Test 
      run : |
        cd Back
        docker-compose up -d
        docker-compose exec -T app php bin/phpunit
