name: Cypress tests
on: [push]
defaults:
    run:
        working-directory: Front
jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Run cypress test
          uses: cypress-io/github-action@v2
          with:
            start: npm start
            working-directory : Front
            wait-on: 'http://localhost:3000'
            config: baseUrl=https://localhost:3000
