name: Cypress Tests

on: [push]
defaults:
    run:
        working-directory: Front
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/included:3.8.3
    steps:
          - name: Checkout
            uses: actions/checkout@v1
            with:
              start: npm start
              wait-on: 'http://localhost:3000'
              config: baseUrl=https://localhost:3000
