name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Run blog test
            uses: cypress-io/github-action@v2
            with:
              start: cd Front && npm start
              wait-on: 'http://localhost:3000'
              config: baseUrl=https://localhost:3000
